// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAakQJz_Lc99RZO51IBWclOV6aQrRVWKM',
    appId: '1:772170984682:web:d1303bf1c73073fbeabb93',
    messagingSenderId: '772170984682',
    projectId: 'driver-management-cb67c',
    authDomain: 'driver-management-cb67c.firebaseapp.com',
    databaseURL: 'https://driver-management-cb67c-default-rtdb.firebaseio.com',
    storageBucket: 'driver-management-cb67c.appspot.com',
    measurementId: 'G-E0Y0M2M5YD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAakQJz_Lc99RZO51IBWclOV6aQrRVWKM',
    appId: '1:772170984682:android:1234567890abcdef',
    messagingSenderId: '772170984682',
    projectId: 'driver-management-cb67c',
    databaseURL: 'https://driver-management-cb67c-default-rtdb.firebaseio.com',
    storageBucket: 'driver-management-cb67c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPSuEiGHRg9cjTQ-qOor8n7c5ML7M4ovI',
    appId: '1:772170984682:ios:a08c6e12224a053deabb93',
    messagingSenderId: '772170984682',
    projectId: 'driver-management-cb67c',
    databaseURL: 'https://driver-management-cb67c-default-rtdb.firebaseio.com',
    storageBucket: 'driver-management-cb67c.appspot.com',
    iosBundleId: 'com.example.TrailerAce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPSuEiGHRg9cjTQ-qOor8n7c5ML7M4ovI',
    appId: '1:772170984682:ios:3eb2be751ba7b16eeabb93',
    messagingSenderId: '772170984682',
    projectId: 'driver-management-cb67c',
    databaseURL: 'https://driver-management-cb67c-default-rtdb.firebaseio.com',
    storageBucket: 'driver-management-cb67c.appspot.com',
    iosBundleId: 'com.example.driverManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAakQJz_Lc99RZO51IBWclOV6aQrRVWKM',
    appId: '1:772170984682:web:4b67c8813cf43c9deabb93',
    messagingSenderId: '772170984682',
    projectId: 'driver-management-cb67c',
    authDomain: 'driver-management-cb67c.firebaseapp.com',
    databaseURL: 'https://driver-management-cb67c-default-rtdb.firebaseio.com',
    storageBucket: 'driver-management-cb67c.appspot.com',
    measurementId: 'G-7L2XV7M4CQ',
  );

}
